server:
  port: 8081

spring:
  h2:
    console:
      enabled: true							# h2 콘솔 사용
      path: /h2									# localhost:port/h2 로 접근 가능
      settings:
        trace: false						# Print additional trace information
        web-allow-others: true	# 브라우저로 접근가능하게 하기
  profiles:
    active: local
  # H2 메모리 DB를 위한 설정
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:searcher;DB_CLOSE_DELAY=-1 # userdb 스키마에 mem인 메모리 데이터 베이스로 동작
    username: sa
    password:
  sql:
    init:
      encoding: utf-8

blog-searcher:
  client:
    rest-api-key:
      kakao: 646fac399c70e29276d821083f298f18