server:
  port: 8081

logging:
  level:
    root: info
    org.hibernate: off
    org.apache.tomcat.util: off
    org.springframework.orm.jpa: off
    org.redisson.connection: debug
    org.springframework.beans.factory.support: debug

spring:
  jpa:
    open-in-view: false
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop

    database-platform: h2
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true

  h2:
    console:
      enabled: true							# h2 콘솔 사용
      path: /h2									# localhost:port/h2 로 접근 가능
      settings:
        trace: false						# Print additional trace information
        web-allow-others: true	# 브라우저로 접근가능하게 하기
  profiles:
    active: local
  # H2 메모리 DB를 위한 설정
  datasource:
    hikari:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:mem:searcher;DB_CLOSE_DELAY=-1 # userdb 스키마에 mem인 메모리 데이터 베이스로 동작
#      jdbc-url: jdbc:h2:tcp://localhost:9094/mem:searcher
      username: sa
      password:

  sql:
    init:
      encoding: utf-8
  redis:
    host: 127.0.0.1
    port: 6379

blog-searcher:
  client:
    host:
      kakao: https://dapi.kakao.com
      naver: https://openapi.naver.com

    rest-api-key:
      kakao: 646fac399c70e29276d821083f298f18
      naver: WxWkwb6YRW

    client-id:
      naver: BIEpxJjpO31vqVNKhAs8